nginx:
  image: nginx
  volumes:
   - docker/nginx/conf.d:/etc/nginx/conf.d:ro
   - docker/nginx/var/log/nginx:/var/log/nginx:rw
   - ./humhub:/code
   - /etc/localtime:/etc/localtime:ro
  ports:
   - "8096:80"
  links:
   - fpm
fpm:
  build: docker/fpm/build
  volumes:
   - docker/fpm/var/log/fpm:/var/log/fpm:rw
   - ./humhub:/code
   - /etc/localtime:/etc/localtime:ro
  links:
   - mysql
mysql:
  image: mysql:5.7
  volumes:
   - docker/mysql/db:/var/lib/mysql
   - docker/mysql/etc/mysql:/etc/mysql:ro
   - docker/mysql/db_backup:/var/backups/mysql:rw
   - docker/mysql/var/log/mysql:/var/log/mysql:rw
   - /etc/localtime:/etc/localtime:ro
  environment:
   MYSQL_ROOT_PASSWORD: toor
   MYSQL_USER: humhub
   MYSQL_PASSWORD: humhub
   MYSQL_DATABASE: humhub


